nelmio_api_doc:
    documentation:
        schemes: [http, https]
        info:
            title: Test API app
            description: Documentation for Test API
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []

    areas: # to filter documented areas
        path_patterns: [ '^/api' ]